import type { SeedEdge } from '../types.js'

export const SEED_NODES = [
  { ticker: 'NVDA',      company: 'NVIDIA Corporation',                themes: ['ai-infrastructure'] },
  { ticker: 'AMD',       company: 'Advanced Micro Devices',             themes: ['ai-infrastructure', 'semiconductors'] },
  { ticker: 'AVGO',      company: 'Broadcom Inc',                       themes: ['ai-infrastructure'] },
  { ticker: 'MRVL',      company: 'Marvell Technology',                 themes: ['ai-infrastructure'] },
  { ticker: 'ARM',       company: 'Arm Holdings plc',                   themes: ['ai-infrastructure', 'semiconductors'] },
  { ticker: 'SMCI',      company: 'Super Micro Computer',               themes: ['ai-infrastructure'] },
  { ticker: 'PLTR',      company: 'Palantir Technologies',              themes: ['ai-infrastructure'] },
  { ticker: 'DELL',      company: 'Dell Technologies',                  themes: ['ai-infrastructure'] },
  { ticker: 'CRWV',      company: 'CoreWeave',                          themes: ['ai-infrastructure'] },
  { ticker: 'TSM',       company: 'Taiwan Semiconductor Manufacturing', themes: ['semiconductors'] },
  { ticker: 'ASML',      company: 'ASML Holding',                       themes: ['semiconductors'] },
  { ticker: 'AMAT',      company: 'Applied Materials',                  themes: ['semiconductors'] },
  { ticker: 'KLAC',      company: 'KLA Corporation',                    themes: ['semiconductors'] },
  { ticker: 'LRCX',      company: 'Lam Research',                       themes: ['semiconductors'] },
  { ticker: 'INTC',      company: 'Intel Corporation',                  themes: ['semiconductors'] },
  { ticker: 'MU',        company: 'Micron Technology',                  themes: ['semiconductors'] },
  { ticker: 'QCOM',      company: 'Qualcomm',                           themes: ['semiconductors'] },
  { ticker: 'WDC',       company: 'Western Digital',                    themes: ['semiconductors'] },
  { ticker: 'MSFT',      company: 'Microsoft Corporation',              themes: ['cloud-hyperscalers'] },
  { ticker: 'AMZN',      company: 'Amazon.com Inc',                     themes: ['cloud-hyperscalers'] },
  { ticker: 'GOOG',      company: 'Alphabet Inc',                       themes: ['cloud-hyperscalers'] },
  { ticker: 'META',      company: 'Meta Platforms',                     themes: ['cloud-hyperscalers'] },
  { ticker: 'ORCL',      company: 'Oracle Corporation',                 themes: ['cloud-hyperscalers'] },
  { ticker: 'IBM',       company: 'IBM',                                themes: ['cloud-hyperscalers'] },
  { ticker: 'NEE',       company: 'NextEra Energy',                     themes: ['energy-infrastructure'] },
  { ticker: 'CEG',       company: 'Constellation Energy',               themes: ['energy-infrastructure'] },
  { ticker: 'VST',       company: 'Vistra Corp',                        themes: ['energy-infrastructure'] },
  { ticker: 'AEE',       company: 'Ameren Corporation',                 themes: ['energy-infrastructure'] },
  { ticker: 'CRWD',      company: 'CrowdStrike Holdings',               themes: ['cybersecurity'] },
  { ticker: 'NET',       company: 'Cloudflare Inc',                     themes: ['cybersecurity'] },
  { ticker: 'APP',       company: 'AppLovin Corporation',               themes: ['adtech'] },
  { ticker: 'ANTHROPIC', company: 'Anthropic',                          themes: ['private'] },
  { ticker: 'OPENAI',    company: 'OpenAI',                             themes: ['private'] },
  { ticker: 'XAI',       company: 'xAI',                               themes: ['private'] },
]

export const SEED_EDGES: SeedEdge[] = [
  // supply_chain: from depends on to for manufacturing/components
  { from: 'NVDA', to: 'TSM',  type: 'supply_chain', strength: 'strong',   description: 'TSMC manufactures NVIDIA GPUs (H100, B200, GB200) at 4nm/3nm nodes' },
  { from: 'AMD',  to: 'TSM',  type: 'supply_chain', strength: 'strong',   description: 'TSMC manufactures AMD CPUs (EPYC, Ryzen) and Instinct GPUs' },
  { from: 'ARM',  to: 'TSM',  type: 'supply_chain', strength: 'moderate', description: 'TSMC fabs chips based on ARM architecture for ARM licensees' },
  { from: 'AVGO', to: 'TSM',  type: 'supply_chain', strength: 'strong',   description: 'TSMC manufactures Broadcom custom AI ASICs and networking chips' },
  { from: 'MRVL', to: 'TSM',  type: 'supply_chain', strength: 'strong',   description: 'TSMC manufactures Marvell custom silicon and networking chips' },
  { from: 'NVDA', to: 'AMAT', type: 'supply_chain', strength: 'moderate', description: 'Applied Materials provides deposition/etch equipment used in NVIDIA GPU fab' },
  { from: 'TSM',  to: 'ASML', type: 'supply_chain', strength: 'strong',   description: 'TSMC depends on ASML EUV lithography for advanced node production' },
  { from: 'TSM',  to: 'AMAT', type: 'supply_chain', strength: 'strong',   description: 'Applied Materials is a major equipment supplier to TSMC fabs' },
  { from: 'TSM',  to: 'KLAC', type: 'supply_chain', strength: 'strong',   description: 'KLA provides process control equipment critical to TSMC yield management' },
  { from: 'TSM',  to: 'LRCX', type: 'supply_chain', strength: 'strong',   description: 'Lam Research provides etch and deposition equipment to TSMC' },
  { from: 'NVDA', to: 'MU',   type: 'supply_chain', strength: 'strong',   description: 'Micron supplies HBM memory stacked on NVIDIA H100/B200 GPUs' },
  { from: 'AMD',  to: 'MU',   type: 'supply_chain', strength: 'moderate', description: 'Micron supplies HBM for AMD Instinct MI300 GPUs' },
  { from: 'SMCI', to: 'NVDA', type: 'supply_chain', strength: 'strong',   description: 'SMCI builds GPU servers using NVIDIA GPUs as primary component' },
  { from: 'DELL', to: 'NVDA', type: 'supply_chain', strength: 'strong',   description: 'Dell PowerEdge AI servers use NVIDIA GPUs as core component' },

  // customer: from is a paying customer of to
  { from: 'CRWV', to: 'NVDA', type: 'customer', strength: 'strong',   description: 'CoreWeave is among the largest NVIDIA GPU customers for neocloud infrastructure' },
  { from: 'MSFT', to: 'NVDA', type: 'customer', strength: 'strong',   description: 'Microsoft Azure is a major NVIDIA GPU customer for cloud AI infrastructure' },
  { from: 'AMZN', to: 'NVDA', type: 'customer', strength: 'strong',   description: 'AWS purchases NVIDIA GPUs alongside its own Trainium/Inferentia silicon' },
  { from: 'GOOG', to: 'NVDA', type: 'customer', strength: 'moderate', description: 'Google Cloud purchases NVIDIA GPUs alongside its own TPU infrastructure' },
  { from: 'META', to: 'NVDA', type: 'customer', strength: 'strong',   description: 'Meta is one of the largest NVIDIA GPU buyers for Llama AI training' },
  { from: 'ORCL', to: 'NVDA', type: 'customer', strength: 'strong',   description: 'Oracle Cloud purchases NVIDIA GPUs for its GPU cloud infrastructure' },
  { from: 'MSFT', to: 'ARM',  type: 'customer', strength: 'strong',   description: 'Microsoft licenses ARM architecture for Azure Cobalt custom CPUs' },
  { from: 'AMZN', to: 'ARM',  type: 'customer', strength: 'strong',   description: 'Amazon licenses ARM for Graviton CPU series powering AWS infrastructure' },
  { from: 'GOOG', to: 'ARM',  type: 'customer', strength: 'strong',   description: 'Google licenses ARM for Axion custom CPU used in Google Cloud' },
  { from: 'PLTR', to: 'MSFT', type: 'customer', strength: 'moderate', description: 'Palantir runs its AIP platform on Azure cloud infrastructure' },
  { from: 'NET',  to: 'AMZN', type: 'customer', strength: 'moderate', description: 'Cloudflare uses AWS as infrastructure alongside its own global network' },

  // technology: from's products run on or are built on to's technology
  { from: 'MSFT', to: 'ARM',  type: 'technology', strength: 'strong',   description: 'Microsoft Azure Cobalt CPU is ARM-architecture based' },
  { from: 'AMZN', to: 'ARM',  type: 'technology', strength: 'strong',   description: 'AWS Graviton CPUs are ARM-based; power significant EC2 capacity' },
  { from: 'GOOG', to: 'ARM',  type: 'technology', strength: 'strong',   description: 'Google Axion CPU is ARM-based' },
  { from: 'CRWV', to: 'NVDA', type: 'technology', strength: 'strong',   description: 'CoreWeave infrastructure is built entirely on NVIDIA GPU technology (CUDA)' },
  { from: 'META', to: 'NVDA', type: 'technology', strength: 'strong',   description: 'Meta AI training runs on NVIDIA GPU clusters using CUDA' },
  { from: 'NET',  to: 'ARM',  type: 'technology', strength: 'moderate', description: 'Cloudflare uses ARM-based servers across its global network edge nodes' },

  // competitive: from and to compete in overlapping markets
  { from: 'NVDA', to: 'AMD',  type: 'competitive', strength: 'strong',   description: 'AMD Instinct GPU line competes with NVIDIA in AI accelerator market' },
  { from: 'NVDA', to: 'INTC', type: 'competitive', strength: 'moderate', description: 'Intel Gaudi AI accelerators compete with NVIDIA in data center AI' },
  { from: 'AMD',  to: 'INTC', type: 'competitive', strength: 'strong',   description: 'AMD EPYC CPUs compete directly with Intel Xeon in data center market' },
  { from: 'MSFT', to: 'AMZN', type: 'competitive', strength: 'strong',   description: 'Azure and AWS are primary competitors in enterprise cloud market' },
  { from: 'MSFT', to: 'GOOG', type: 'competitive', strength: 'strong',   description: 'Azure and Google Cloud compete in enterprise cloud and AI services' },
  { from: 'AMZN', to: 'GOOG', type: 'competitive', strength: 'strong',   description: 'AWS and Google Cloud are direct competitors in cloud infrastructure' },
  { from: 'TSM',  to: 'INTC', type: 'competitive', strength: 'moderate', description: 'Intel Foundry Services competes with TSMC for advanced semiconductor fabrication' },
  { from: 'ARM',  to: 'INTC', type: 'competitive', strength: 'moderate', description: 'ARM-based server CPUs (Graviton, Cobalt, Axion) compete with Intel Xeon' },
  { from: 'CRWD', to: 'NET',  type: 'competitive', strength: 'weak',     description: 'CrowdStrike and Cloudflare overlap in zero-trust and network security markets' },
  { from: 'OPENAI', to: 'ANTHROPIC', type: 'competitive', strength: 'strong', description: 'OpenAI and Anthropic are direct competitors in frontier AI model market' },
  { from: 'OPENAI', to: 'XAI',       type: 'competitive', strength: 'strong', description: 'OpenAI and xAI compete in AI assistant and frontier model market' },
]
